# Site settings
title: Michael H&uuml;bl
description: Entrepreneur, Speaker, Coach
keywords: Entrepreneur, Speaker, Coach
author: Michael H&uuml;bl
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
